### PR TITLE
Close loops

### LINKED ISSUE #60: 🐞 Bug: Renban drawing
### Describe the Bug

When drawing a renban line, if you go back over part of the line that is already drawn, it erases everything past that point. If you wanted to draw a T shape, for example, you wouldn't be able to.
Something like this image, but all connected. image

https://user-images.githubusercontent.com/72059631/152445166-4b22db67-fc4f-4687-a44d-0befa26745ad.mp4

.

### Reproduction steps

_No response_

### Sudoku Studio Save Url

_No response_

### Sudoku Studio Version

0c0bad9

### Browser Version

Chrome/97.0.4692.99

### OS Version

Win 10

### PR DESCRIPTION
**Pull request by degustaf**
For lines that loop, ands don't matter (whispers and renban) make the lines actually loop.
Palindrome lines should be unaffected

image

Closes #60

### CODE REVIEW

**Comment by wooferzfg** [comment]
Is there a way to handle this in a more generic way, that also covers cases like this? 
Screenshot_20230109_150032_Chrome

**Comment by wooferzfg** [comment]
Also, I think https://github.com/SudokuStudio/SudokuStudio/issues/60 might be resolved already / resolved by this PR?

**Comment by degustaf** [comment]
Good catch.

How do we want to handle this case? Should they be separate renbans, or should we treat them as one?
image

**Comment by degustaf** [comment]
Should be fixed.

image


And, yes. I beleive it does close #60.

**Pull request merged**
